// ─── VENDOR & MATERIAL DATA LIBRARY ──────────────────────────────────────────

export const vendors = [
  // WOODWORK
  {
    id: "greenply",
    name: "Greenply",
    category: "Woodwork",
    tier: ["Economical"],
    classification: "Standard",
    priceRange: "₹38–65 / sq ft",
    finishTypes: ["Natural Veneer", "Laminate Ready", "Pre-Finished"],
    texturePreviews: ["Oak Veneer", "Teak Natural", "Wenge Dark"],
    description: "India's most trusted plywood brand. Durable, ISI-certified, widely available across tier-1 and tier-2 cities.",
    status: "Active",
    origin: "India",
    leadTime: "3–5 days",
    moq: "50 sheets",
    rating: 4.2,
    projectsCompleted: 184,
    contactEmail: "vendor@greenply.co.in",
    specialty: ["Plywood", "MDF", "Blockboard"],
  },
  {
    id: "kitply",
    name: "Kitply",
    category: "Woodwork",
    tier: ["Economical"],
    classification: "Standard",
    priceRange: "₹42–70 / sq ft",
    finishTypes: ["Birch Core", "Gurjan Core", "Marine Grade"],
    texturePreviews: ["Birch Natural", "Gurjan Brown", "Marine White"],
    description: "Consistently reliable plywood for modular kitchens and wardrobes. Strong ISI mark track record.",
    status: "Active",
    origin: "India",
    leadTime: "4–6 days",
    moq: "40 sheets",
    rating: 4.0,
    projectsCompleted: 127,
    contactEmail: "orders@kitply.com",
    specialty: ["Kitchen Cabinets", "Wardrobes", "Structural Panels"],
  },
  {
    id: "centuryply",
    name: "CenturyPly",
    category: "Woodwork",
    tier: ["Premium"],
    classification: "Premium",
    priceRange: "₹72–120 / sq ft",
    finishTypes: ["Club Prime", "Sainik", "Architect", "Club Tech"],
    texturePreviews: ["Teak Premium", "Rosewood", "Maple Blonde", "Ebony Dark"],
    description: "The premium architect's choice in Indian plywood. Anti-borer, moisture-resistant, superior dimensional stability.",
    status: "Preferred",
    origin: "India",
    leadTime: "5–7 days",
    moq: "30 sheets",
    rating: 4.7,
    projectsCompleted: 312,
    contactEmail: "architects@centuryply.com",
    specialty: ["Architect-grade Panels", "Fire Retardant", "Moisture Proof"],
  },
  {
    id: "action-tesa",
    name: "Action TESA",
    category: "Woodwork",
    tier: ["Premium"],
    classification: "Premium",
    priceRange: "₹85–140 / sq ft",
    finishTypes: ["Prelam", "Natural Veneer", "Premium Gloss"],
    texturePreviews: ["Nordic Oak", "American Walnut", "Italian Ash"],
    description: "German engineering meets Indian manufacturing. Prelam boards with European finishes for luxury interiors.",
    status: "Preferred",
    origin: "India (German Tech)",
    leadTime: "7–10 days",
    moq: "20 sheets",
    rating: 4.6,
    projectsCompleted: 245,
    contactEmail: "designdesk@actiontesa.com",
    specialty: ["Prelam Boards", "Custom Sizes", "European Finishes"],
  },

  // HARDWARE
  {
    id: "godrej",
    name: "Godrej",
    category: "Hardware",
    tier: ["Economical"],
    classification: "Standard",
    priceRange: "₹250–800 / piece",
    finishTypes: ["Chrome", "Stainless", "Powder Coated"],
    texturePreviews: ["Polished Chrome", "Matt Silver", "Black"],
    description: "India's benchmark for locks, hinges and security hardware. Trusted by generations of homeowners.",
    status: "Active",
    origin: "India",
    leadTime: "2–4 days",
    moq: "10 units",
    rating: 4.3,
    projectsCompleted: 520,
    contactEmail: "trade@godrej.com",
    specialty: ["Locks", "Hinges", "Drawer Systems"],
  },
  {
    id: "inox",
    name: "Inox",
    category: "Hardware",
    tier: ["Economical", "Premium"],
    classification: "Standard",
    priceRange: "₹180–1200 / piece",
    finishTypes: ["Satin Nickel", "Antique Bronze", "Rose Gold", "Matt Black"],
    texturePreviews: ["Brushed Nickel", "Antique Bronze", "Matt Black"],
    description: "Premium architectural hardware from Italy's INOX group. Elegant door handles and accessories.",
    status: "Active",
    origin: "Italy / India",
    leadTime: "5–8 days",
    moq: "5 units",
    rating: 4.5,
    projectsCompleted: 290,
    contactEmail: "india@inoxdesign.it",
    specialty: ["Door Handles", "Levers", "Architectural Hardware"],
  },
  {
    id: "hettich",
    name: "Hettich",
    category: "Hardware",
    tier: ["Premium"],
    classification: "Premium",
    priceRange: "₹800–4500 / piece",
    finishTypes: ["Nickel Matt", "Stainless Steel", "Soft Gold"],
    texturePreviews: ["Soft-Close Chrome", "Steel Matt", "Champagne Gold"],
    description: "German precision engineering for soft-close systems, pull-outs and lift mechanisms. Industry gold-standard.",
    status: "Preferred",
    origin: "Germany",
    leadTime: "10–14 days",
    moq: "1 unit",
    rating: 4.9,
    projectsCompleted: 408,
    contactEmail: "india@hettich.com",
    specialty: ["Soft-Close Hinges", "Drawer Systems", "Lift Mechanisms"],
  },
  {
    id: "blum",
    name: "Blum",
    category: "Hardware",
    tier: ["Ultra Premium"],
    classification: "Luxury",
    priceRange: "₹2500–18000 / piece",
    finishTypes: ["Orion Grey", "Silk White", "Terra", "Anthracite"],
    texturePreviews: ["Orion Steel", "Silk White", "Anthracite Matt"],
    description: "Austrian luxury hardware brand. MOVENTO, AVENTOS and TANDEM systems define the pinnacle of kitchen and wardrobe engineering.",
    status: "Preferred",
    origin: "Austria",
    leadTime: "14–21 days",
    moq: "1 unit",
    rating: 5.0,
    projectsCompleted: 186,
    contactEmail: "trade@blum.com",
    specialty: ["MOVENTO Runners", "AVENTOS Lifts", "SERVO-DRIVE"],
  },
  {
    id: "hafele",
    name: "Häfele",
    category: "Hardware",
    tier: ["Ultra Premium"],
    classification: "Luxury",
    priceRange: "₹1800–15000 / piece",
    finishTypes: ["Matte Black", "Brushed Brass", "Stainless", "Chrome"],
    texturePreviews: ["Brushed Brass", "Matte Black", "Polished Chrome"],
    description: "German precision hardware and fittings for luxury interiors. Comprehensive range from architectural to furniture hardware.",
    status: "Preferred",
    origin: "Germany",
    leadTime: "7–14 days",
    moq: "1 unit",
    rating: 4.9,
    projectsCompleted: 334,
    contactEmail: "luxury@hafele.com",
    specialty: ["Architectural Fittings", "Smart Locks", "Lighting Integration"],
  },

  // LAMINATE
  {
    id: "virgo",
    name: "Virgo",
    category: "Laminate",
    tier: ["Economical"],
    classification: "Standard",
    priceRange: "₹28–55 / sq ft",
    finishTypes: ["Gloss", "Matt", "Suede", "Texture"],
    texturePreviews: ["Ivory Gloss", "Oak Texture", "Concrete Matt"],
    description: "Value-for-money laminates with good color consistency. Suitable for budget residential and commercial projects.",
    status: "Active",
    origin: "India",
    leadTime: "3–5 days",
    moq: "10 sheets",
    rating: 3.9,
    projectsCompleted: 398,
    contactEmail: "sales@virgolaminate.com",
    specialty: ["Standard Laminates", "Solid Colors", "Woodgrain"],
  },
  {
    id: "marino",
    name: "Marino",
    category: "Laminate",
    tier: ["Premium"],
    classification: "Premium",
    priceRange: "₹65–120 / sq ft",
    finishTypes: ["Sync Gloss", "Aqua Matt", "Metallic", "3D Texture"],
    texturePreviews: ["Brushed Gold Metal", "Marble White", "Concrete Steel"],
    description: "Designer laminates with contemporary aesthetics. Metallic and textured finishes for upscale interiors.",
    status: "Preferred",
    origin: "India",
    leadTime: "5–8 days",
    moq: "5 sheets",
    rating: 4.5,
    projectsCompleted: 267,
    contactEmail: "design@marinolaminate.com",
    specialty: ["Metallic Finishes", "Digital Print", "High Gloss"],
  },
  {
    id: "merino",
    name: "Merino",
    category: "Laminate",
    tier: ["Premium", "Ultra Premium"],
    classification: "Premium",
    priceRange: "₹85–180 / sq ft",
    finishTypes: ["Exteria", "Anti-fingerprint Matt", "Brushed Metal", "Tuff Series"],
    texturePreviews: ["Brushed Titanium", "Ivory Leather", "Dark Walnut"],
    description: "India's premium laminate brand. Anti-fingerprint, scratch-resistant surfaces with European design sensibility.",
    status: "Preferred",
    origin: "India",
    leadTime: "7–10 days",
    moq: "3 sheets",
    rating: 4.7,
    projectsCompleted: 445,
    contactEmail: "architects@merinolam.com",
    specialty: ["Anti-Fingerprint", "Scratch Resistant", "Luxury Decors"],
  },
  {
    id: "royale-touche",
    name: "Royale Touche",
    category: "Laminate",
    tier: ["Ultra Premium"],
    classification: "Luxury",
    priceRange: "₹140–380 / sq ft",
    finishTypes: ["Leather Emboss", "Sync Pore", "Gold Foil", "Stone Effect"],
    texturePreviews: ["Gold Leather", "Marble Veined", "Obsidian Black"],
    description: "Ultra-luxury decorative surfaces for the discerning client. Italian design influences with bespoke finish options.",
    status: "Limited",
    origin: "India / Italy",
    leadTime: "14–21 days",
    moq: "2 sheets",
    rating: 4.8,
    projectsCompleted: 89,
    contactEmail: "luxury@royaletouche.com",
    specialty: ["Decorative Panels", "Feature Walls", "Custom Prints"],
  },

  // GLASS
  {
    id: "ais-glass",
    name: "AIS Glass",
    category: "Glass",
    tier: ["Economical", "Premium"],
    classification: "Standard",
    priceRange: "₹120–450 / sq ft",
    finishTypes: ["Clear Float", "Frosted", "Tinted", "Tempered"],
    texturePreviews: ["Clear Float", "Acid Etched", "Bronze Tinted"],
    description: "India's integrated glass manufacturer. Full product range from basic float to smart glass solutions.",
    status: "Active",
    origin: "India",
    leadTime: "7–14 days",
    moq: "50 sq ft",
    rating: 4.3,
    projectsCompleted: 356,
    contactEmail: "trade@aisglass.com",
    specialty: ["Float Glass", "Lacquered Glass", "Patterned Glass"],
  },
  {
    id: "saint-gobain",
    name: "Saint-Gobain",
    category: "Glass",
    tier: ["Premium", "Ultra Premium"],
    classification: "Luxury",
    priceRange: "₹280–1800 / sq ft",
    finishTypes: ["Miralite Pure", "Satinovo", "Lacobel", "Stadip Silence"],
    texturePreviews: ["Crystal Clear", "Satin Frost", "Lacobel White", "Bronze Mirror"],
    description: "World's leading glass manufacturer. From architectural curtain walls to bespoke privacy and decorative glass.",
    status: "Preferred",
    origin: "France / India",
    leadTime: "14–28 days",
    moq: "100 sq ft",
    rating: 4.9,
    projectsCompleted: 278,
    contactEmail: "architects@saint-gobain.com",
    specialty: ["Acoustic Glass", "Smart Glass", "Decorative", "Structural"],
  },
];

// ─── PACKAGE CONFIGURATIONS ───────────────────────────────────────────────────

export const packageConfigs = [
  {
    tier: "Economical",
    tagline: "Crafted with care, delivered with value",
    color: "#8B7355",
    accentColor: "#C4A882",
    priceMultiplier: "1x",
    startingPrice: "₹1.2L / room",
    materialQuality: "ISI-certified, durable Indian brands",
    vendorTier: "Standard",
    consultationRate: "₹5,000 / session",
    estimatedTimeline: "4–6 weeks",
    features: [
      "Single room design",
      "2D layout + mood board",
      "Budget material sourcing",
      "Standard finish selection",
      "2 revision rounds",
      "Digital quotation",
    ],
    materials: ["Greenply / Kitply plywood", "Godrej hardware", "Virgo laminates", "AIS float glass", "Standard tiles"],
    hospitality: ["Functional furniture", "Basic linen sets", "Standard lighting plan", "Essential décor"],
    designStyle: ["Contemporary", "Functional Modern", "Indo-Minimal"],
    moodPalette: ["Warm White", "Beige", "Oak Natural", "Soft Grey"],
    recommendedVendors: ["greenply", "kitply", "godrej", "virgo", "ais-glass"],
  },
  {
    tier: "Premium",
    tagline: "Refined materials, elevated living",
    color: "#8B5A2B",
    accentColor: "#C17F3D",
    priceMultiplier: "3–5x",
    startingPrice: "₹6.5L / residence",
    materialQuality: "German & premium Indian brands with superior finishes",
    vendorTier: "Premium",
    consultationRate: "₹15,000 / session",
    estimatedTimeline: "8–12 weeks",
    features: [
      "Up to 3 rooms / full home",
      "Full 3D walkthrough",
      "Premium material curation",
      "Procurement managed",
      "On-site styling visit",
      "4 revision rounds",
      "Itemised quotation",
      "Contractor coordination",
    ],
    materials: [
      "CenturyPly / Action TESA boards",
      "Hettich soft-close hardware",
      "Marino / Merino laminates",
      "Saint-Gobain glass",
      "Italian porcelain tiles",
    ],
    hospitality: [
      "Bespoke furniture selection",
      "Curated art placement",
      "Hospitality-grade linen",
      "Layered lighting design",
      "Signature accent pieces",
    ],
    designStyle: ["Modern Luxury", "Scandinavian", "Contemporary Chic", "Transitional"],
    moodPalette: ["Warm Ivory", "Travertine", "Walnut", "Brushed Brass", "Sage"],
    recommendedVendors: ["centuryply", "action-tesa", "hettich", "marino", "merino", "saint-gobain"],
  },
  {
    tier: "Ultra Premium",
    tagline: "No compromise. Total architectural mastery.",
    color: "#5C3D2E",
    accentColor: "#8B5E3C",
    priceMultiplier: "10–20x",
    startingPrice: "₹15L+ / bespoke",
    materialQuality: "European luxury imports, bespoke commissions, smart systems",
    vendorTier: "Luxury",
    consultationRate: "₹50,000 / session",
    estimatedTimeline: "16–24 weeks",
    features: [
      "Complete residence / estate",
      "Architectural coordination",
      "Imported luxury materials",
      "Custom commissioned furniture",
      "Personal design director",
      "Smart home integration",
      "White-glove installation",
      "Editorial photography",
      "Post-install styling",
      "Priority concierge support",
    ],
    materials: [
      "Austrian Blum hardware systems",
      "Häfele architectural fittings",
      "Royale Touche decorative panels",
      "Saint-Gobain smart / acoustic glass",
      "Imported marble & onyx",
      "Custom solid wood joinery",
    ],
    hospitality: [
      "End-to-end architecture",
      "Bespoke furniture commissions",
      "Curated art acquisition",
      "Smart hospitality systems",
      "Operational staff training",
      "PR & editorial launch",
      "Fragrance identity",
    ],
    designStyle: ["Architectural Luxury", "Editorial Calm", "Maximalist Restraint", "Japandi Luxury"],
    moodPalette: ["Onyx", "Travertine White", "Cognac Leather", "Brushed Gold", "Deep Velvet", "Alabaster"],
    recommendedVendors: ["blum", "hafele", "royale-touche", "saint-gobain", "merino"],
  },
];

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export function getVendorsByTier(tier) {
  return vendors.filter((v) => v.tier.includes(tier));
}

export function getVendorsByCategory(category) {
  return vendors.filter((v) => v.category === category);
}

export function getPackageConfig(tier) {
  return packageConfigs.find((p) => p.tier === tier);
}

export function getVendorById(id) {
  return vendors.find((v) => v.id === id);
}

export const materialCategories = ["Woodwork", "Hardware", "Laminate", "Glass"];

export const allTiers = ["Economical", "Premium", "Ultra Premium"];
